### ISSUE TITLE
BD zoom checklist for good recordings

### ISSUE THREAD

**Issue by naomitress** [ocean-tracking-network/node-manager-training#25]
need the settings for the day of

**Comment by jackVanish** [comment]
With Zoom open, click 'Zoom.us' in the top menu bar and then click 'Preferences' (or Settings on Windows, whichever seems appropriate). 

- In the "Video" tab, uncheck the box next to "Always display participant name on their videos."
- In the "Recording" tab, uncheck the box next to "Record video during screen sharing." 
- When the call starts, but before you start recording, make sure you are in Speaker view. Mouse over your video in the top bar, click the blue button with the ellipsis on it, and select 'Pin Video'. 

These settings will replicate those I had active when I recorded this video with Caitlin: https://otn.slack.com/archives/G01G37SEEP4/p1646934942051969 ideally, test these before the workshop to make sure they work for you too, so that I know if I have to go in and wrangle more settings. If they work fine for you, then you can close this ticket.

**Comment by jackVanish** [comment]
I never heard anything else about this ticket so I assume everything worked fine and everyone was happy. Closing the ticket.
