### ISSUE TITLE
compare nodemananger curriculum to ipython utilities

### ISSUE THREAD

**Issue by naomitress** [ocean-tracking-network/node-manager-training#44]

**Comment by naomitress** [comment]
- when was nmt -gh pages last updated (for each module)
- when was ipython utilities -master branch- last update (for each module)

**Comment by naomitress** [comment]
for each nmt module that is behind, make an issue to update

**Comment by naomitress** [comment]
@jackVanish will confirm when this can be done by

**Comment by jackVanish** [comment]
I've had a look into this and while I know the original ask was to only do this for the episode modules that are behind, it looks like every set of notebooks has received an update since the episodes were last edited. With the exception of the movers notebooks and the setup, every episode in the NMT curriculum was last updated two years ago. The notebooks referenced- Create and Update Projects, the Tag notebook series, the Deploy notebook, and the Detections notebook series- have all received updates between a year and a few months ago, so they're all newer than their associated lessons. 

Since we now have a newer ticket for making updates to each notebook-related NMT section (https://github.com/ocean-tracking-network/node-manager-training/issues/49), I propose that we close this, and break the NMT cleanup ticket into notebook-specific chunks, sorting out the feedback in @slandovs and @CaitlinBate's comments into individual tickets, per this ticket's ask. 

If @jdpye signs off on that then I'll close this ticket and make the new ones based on what's in ticket 49 linked above.
