### ISSUE TITLE
detections lesson fixes

### ISSUE THREAD

**Issue by CaitlinBate** [ocean-tracking-network/node-manager-training#46]
- fix rcvr_config section of the lesson
- add explanation in load sentinel tags section (only load the years relevant to the ticket)

**Comment by slandovs** [comment]
- add explanation in load sentinel tags section (only load the years relevant to the ticket)

**Comment by jackVanish** [comment]
I've taken these bullets and added them into https://github.com/ocean-tracking-network/node-manager-training/issues/61, which also captures todos from https://github.com/ocean-tracking-network/node-manager-training/issues/49. I'm closing this ticket so that we can track work in https://github.com/ocean-tracking-network/node-manager-training/issues/61 going forward.
