### ISSUE TITLE
Add workflow diagrams to data loading workflows lesson

### ISSUE THREAD

**Issue by jdpye** [ocean-tracking-network/node-manager-training#48]
We've (@naomitress , @diniangela , @jdpye ) built some workflow diagrams in Miro that describe the data loading process and who's involved, and what the decision points are. We should build them into the lesson about data loading workflows. Especially since people crib diagrams and other figures from this lesson set for presentations etc.

Can do ones from miro (and create ones that are discussed in node manager training):
- [ ] Path of data
- [ ] Project metadata (with notebook names)
- [ ] Tag metadata (with notebook names)
- [ ] Receiver metadata (with notebook names)
- [ ] Detection data (with notebook names)
- [ ] Data push
- [ ] Database fix notebooks

**Comment by diniangela** [comment]
Added a pull request for this work: https://github.com/ocean-tracking-network/node-manager-training/pull/81

**Comment by jackVanish** [comment]
Mermaid needed a little crunch to make it work: _includes/javascript.html now has the mermaid script call, and the flowchart diagrams use `<pre class="mermaid"></pre>` instead of code blocks to make them render. I've tweaked the code as necessary and now leave it to Angela to inspect the flowcharts and make sure they look OK.

**Comment by diniangela** [comment]
They look good on the website so closing this ticket now
