### ISSUE TITLE
NMT clean up:

### ISSUE THREAD

**Issue by CaitlinBate** [ocean-tracking-network/node-manager-training#49]
- Movers need a lesson. the old notebooks are currently mentioned in the Supplementary Notebooks lesson and are out of date.
- DB fix notebooks will need their own lesson before they become live
- all checklists at the beginning of proj. tag, deploy, det lessons need updating
- `AUTH - Create and Update`  section of the "data loading workflow" lesson should probably be moved to its own lesson? and include info about gitlac access tokens etcs?
- convert - Fathom (vdat) Export - VRL to CSV section of dertection loading likely needs to be expanded A LOT
- all "verification of file contents" sections of Tag lesson AND deployment lesson needs to be reviewed for completness
- "verifying cache" and "verifying otn tables" sections need to be checked for completeness
- events-4 portion of the detections lesson is NOT complete, there have been changes since the lesson was written

**Comment by slandovs** [comment]
- Setup and Installing: I think the "More Useful Programs" section could provide more context for why these are useful (for example, path copy copy for windows users so that they can copy and paste paths directly rather than having to make changes to the pasted path)

Project meta: 
- under "Project Metadata Parser" I think the 1. and 2. at the top need to be explained more clearly as two distinct cells and you only choose one of them to run. A good example of this is further down in the module, under "Access Project Info"
- under "Manual Fields - Dropdown Menu", shortname is usually the project code, not the title provided by the researcher
- under "Skip to Verification" there is a small typo - "You should enter run these cells..." should not have "enter"

Tag Metadata: 
- are we keeping it as "floy" or should all of this be changed to reflect the more general word we are using (can't remember what it is). I dont think this has been changed in the DB yet but maybe recording this for the future to change?
- typo under "Verification of File Contents - formatting" in the second sentence "Generally, it will be names ...." should be "named"
- under "Checking for Duplicates" could add a larger statement about how if no duplicates are found, you can move onto the next notebook (currently just says "you can move on"
- under "Verifying OTN Tables" we have a line that says "If there are any errors, go into the database and fix the otn tables themselves," i think this should be altered. We can refer to the db fix module here instead?

Deploy metadata: 
- we don't have any explanation for the "check that station locations have not changed stations "NAMES"" line of the template (under "Loading the Raw Table")
- under "Load the events file into the c_events_yyyy table" it says "Upon successful loading and can dispose of the engine..." but should say "Upon successful loading, you can dispose..." or something like that

detections: 
- agree with CB, need much more detail under 'Convert to CSV' 
- for both the dets 3b and dets 3c sections, after it says "track this information in a new GitLab ticket" add something like "and then you can continue on with the notebooks"

Supplementary: 
- can we put a link to the more thorough description of the "convert - fathom..." notebook (in detections module) here?
- will "active tracking" still be used with the updates to the movers notebooks? if not, this part should be removed. 
- the "slocum telemetry notebook" and the "telemetry processing for wave gliders and animals" can be removed since there will be a movers module
- section on the receiver operator notebook needs to either be removed, or reflect the new name and state it is for internal use only and NOT a summary report for receiver operators (we are making a new notebook for this, but it will not be in this folder)
- remove the "DB-Fix notebooks" section since they will have their own module

- The Push: update the push schedule (do we want to update it with actual dates, or just have third thursday of the following months each year: February, June, October" so it doesn't need to updated yearly?

Fixing Data Errors: 
- db fix module will be added in here?
- also needs an update to the template in here

general: 
- for "Final Steps" sections (or anywhere else) that it says "passed off to an OTN-analyst" we should add some language for those nodes that do not pass to us for verification
- same with when it says "contact an OTN database staff member to resolve these" (for example in the deploy metadata)
- inconsistent use of 'notebook' and 'nodebook' throughout

- as CB mentioned, adding the movers module (YN working on that)

**Comment by jdpye** [comment]
We should generate a branch for this cleanup step and have a few people validate it and add changes to things they are specialized in (events, movers) to make the best thing we can.

**Comment by jackVanish** [comment]
Made a branch at 2024_training_cleanup that we can all foist our changes into.

**Comment by jackVanish** [comment]
I have split this ticket up into a bunch of different tickets with task lists to individually track changes to each lesson. These tickets capture everything in this ticket, plus one other detections related ticket (#46 ), since closed. The new tickets are assigned to either Caitlin or myself, to be reassigned as necessary. Since the work for this ticket is now captured more cleanly, I'm closing this ticket.
