### ISSUE TITLE
renumber lessons based on order of teaching

### ISSUE THREAD

**Issue by CaitlinBate** [ocean-tracking-network/node-manager-training#78]
once this is done, make changes to the order of the lessons https://github.com/ocean-tracking-network/node-manager-training/blob/2024_agenda_and_jon_edits/README.md

current plan:

welcome/ intro
upholding data policy **not sure where this goes**
otn system structure and outputs
setup
data loading workflow
auth notebook
project metadata
tag metadata
deployment metadata
detection loading
movers
viz notebooks
db fix notebooks
data push
detection extracts
supplementary notebooks
notebook improvement and develipment

**Comment by jackVanish** [comment]
@jdpye I can handle this with a few quick clarifications: 
- Do we know where Upholding Data Policy goes?
- Is 'Detection Extracts' covered in the 'Data Push' lesson (it looks like it is but I want to be sure). 

Otherwise it looks like everything is here so I can have this done quickly and quietly.

**Comment by jdpye** [comment]
Upholding the Data Policy slots in directly after the introduction from me.

Detection Extracts is covered in the Data Push lesson as far as I know.

**Comment by jackVanish** [comment]
Relevant merge request has been merged, closing this ticket.
